src/JobsView.vala

This makes sure that the ScrolledWindow is shown so that it can be set to the visible child of the stack.
Fixes #25

Ensure that jobs can made visible

---

src/JobsView.vala

This allows jobs that have been paused to be cancelled without having to resume, which may cause them to start printing and as such not cancel. This is related to #24, but there are more issues causing that problem.

Allow cancelling halted jobs

---

src/PrinterPage.vala

This saves the printer location name users have typed in when they press enter, and also when the popover hides, it resets to the current printer location as it keeping the name may imply it has saved it when it has not. This issue was raised in #14.

Allow renaming printer location

---

src/Plug.vala

It is not valid and causes warnings during compilation.

Remove static modifier from constants

---

src/Objects/Job.vala

Currently Job emits no signal when pausing or resuming as job_state is emitted rather than job_state_changed by Notifier, this corrects that behaviour and emits on job_state too.

Emit state_changed when pausing/resuming

---

src/JobsView.vala

This uses ListBox in place of ListStore as it better handles random access, whilst ListStore is better for sequential access that only happens once, when removing completed jobs, whereas random accesses happen when a job is paused, resumed, stopped or the selected row is changed, and in this when the state of the job changes as the ListBoxRow makes it trivial to implement. This also has the benefit that it makes the progress Spinner actually spin (we would have needed to pulse the previous one to do this which was not nice to implement.) 
On the UX side it is generally kept the same aside from the Spinner, with the exception of margins: I have added a slight horizontal margin to the jobs, I think it makes them feel more comfortable in their place rather than squashed against the side.

Use ListBox instead of ListStore and TreeView

---

src/InkLevel.vala

This probably fixes #33, but even if not it is good to have added safety on the gets, I think only the marker-names is likely to exceed colors.size, but again it's good for safety.

Ensure arraylist gets are within bounds

---

src/InkLevel.vala

This is a basic solution to #35, it falls back to Blueberry when the colour is "none", and if there are multiple it will use the first one. This prevents the warning and allows the css to be applied.
Fixes #35.

Better handle ink colours

---

src/JobsView.vala

Change strings for jobs queue placeholder

---

src/OptionsPage.vala

* Use GObject style
* Don't use methods for things that are only done once
* Get rid of extra grids
* Refactor pages per sheet a bit so that:
* Variable names don't conflict
* Avoid and unnecessary cast
* Don't hide if there's only one option, just set insensitive
I was about to do a bunch of shit in one branch but then I stopped and said "Hey one at a time". My eventual goal here is to get rid of this row_index stuff, show all the options and just make unavailable ones insensitive with feedback that makes sense (like the print dialog), and add some section headers

OptionsPage: use GObject style

---

src/OptionsPage.vala
src/PrinterPage.vala

* Remove extra margin around setup page so that the whole stack has the same margins
* Double space rows so that tab navigation is more obvious
* Bump copyright
* GObject style
* Organize
* Remove extra grids
* Remove unnecessary cast
* Remove unnecessary expands

PrinterPage Cleanups

---

src/Widgets/AddDialog.vala

* gets rid of the whole stack for the loading screen and instead uses the placeholder function of the listbox in the device grid. This destroys a lot fewer widgets when refreshing :p 
* puts the buttons for that screen in a Gtk.ButtonBox so that they're homogenous
* Gives the devices list a frame
* Fixes margins and padding
* Adds an explanation label to the loading screen

AddDialog: Move device grid to construct, clean up

---

src/Objects/Printer.vala
src/Widgets/PrinterRow.vala

Assign icon and override label when printer is disabled. Otherwise, check `printer.state_reasons_raw` to assign an appropriate icon severity

More accurately match printer state to icon

---

src/PrinterPage.vala

According to the [documentation](https://valadoc.org/gobject-2.0/GLib.BindingFlags.html) the `SYNC_CREATE` flag syncs from the source to the target on creation. In this case, it is important for the printer to be the source of truth and for the switch to be the target. Otherwise the printer gets disabled as soon as you load up this plug. Should close #97 and probably a handful of other related issues.

Fix issue where printers are disabled upon viewing in plug

---

src/CUPSNotifier.vala

https://gitlab.gnome.org/GNOME/glib/commit/5a74c2f445458c037aa71ac51de3ed6af325a1ab

Allow the sender parameter of DBusSignalCallback to be null

---

debian/control

Reverts elementary/switchboard-plug-printers#143
I found this might not be correct here because the packaging version is still 5.5.0, although the library version itself is now 6.0.0. This should fix the gettext actions still failing in this repo even after elementary/actions#59 was fixed.

Revert "Control: bump granite dep to 6"

---

src/Plug.vala
src/config.vala.in
src/meson.build

Provides the directory where the locales are actually installed.
We are [packaging this](https://github.com/NixOS/nixpkgs/pull/130380#issuecomment-895720580) in NixOS, and due to NixOS 's special `localedir`, we cannot apply the translations without this patch.
Thanks in advance for reviewing this :-)

l10n: Correctly setup the locales

---

src/Dialogs/AddDialog.vala
src/PrinterList.vala

Modifies #158 
An attempt to implement @danrabbit 's design for the printer driver info, using a listbox.
Constructing the listbox synchronously resulted in the interface freezing for a noticeable time for e.g. HP as there are nearly 5000 entries in that case. This was improved by making the construction asynchronous and cancellable.

Use two lines for printer driver info in Add Dialog

---

src/CUPSNotifier.vala
src/Objects/Job.vala
src/Objects/Printer.vala
src/Views/JobsView.vala
src/Widgets/JobRow.vala

Fixes #71
Fixes #72
Fixes #13 (start/stop buttons)
The linked issue was partly caused by changes in the job status not being properly detected and no `changed ()` signal being emitted when the row was updated.
The issue was fixed in a similar way to #168:
* The CUPS.Job struct that the Printers.Job Object is initialised with is no longer relied on to automatically update. Instead signals from CUPS.Notifier is used to change our own properties on Printers.Job.
* Also the "hold" state of the job is no longer determined by an IPP request (that did not work) but tracked from the initial state and notifier signals.
* Handling of some notifier signals is merged
* The absolute time/date a job was created/completed is displayed except for canceled or aborted jobs.
* When a job row is updated the …

Sync job status

---

src/Objects/Job.vala
src/Widgets/JobRow.vala

Redesign job rows to match rows in other places like Bluetooth settings and Mail
* Use a 32px icon for documents
* Overlay the status icon
* Don't base action availability on the existence of status icons
* More accurate status icons for states like pause, cancel, aborted
* Use `small-label` for status labels
* Always use relative date time and use `dim-label` for date label
* Use label button for pause/resume. Much easier to click right next to the scrollbar or when you're in a panic
* Update pause/resume label on state change, not on button click
* Code style and use Gtk.Box instead of grid, explicit margins to ease Gtk4 porting

JobRow: Redesign and code clean

---

src/Widgets/JobRow.vala

At present, the action revealer unexpectedly hides when a job is pending meaning it cannot be cancelled or paused.  This PR fixes that.

Allow pausing and canceling pending jobs

---

src/Dialogs/AddDialog.vala
src/PrinterList.vala
src/meson.build

Cherry from #164 plus fixes
* Use Hdy.Window instead of Granite.Dialog. Fixes margins since we don't use any dialog functions and don't want the action area. Can replace with Gtk.Window in GTK4, same as Online Accounts dialogs
* Code style
* Use child property
* replace shadow with frame
* Replace grids with boxes
* Vertical form layout with Granite.HeaderLabel for responsive
* Use default size instead of size request
* Replace buttonbox with box

AddDialog: Gtk4 Prep

---

src/PrinterList.vala

* bump copyright header
* Subclass box instead of grid
* code style
* explicit expands
* Do button with label and icon in GTK 4 friendly way
* Remove dialog magic since it's modal
* Replace INLINE_TOOLBAR with FLAT

PrinterList: GTK4 prep

---

src/Dialogs/AddDialog.vala
src/Widgets/ErrorRevealer.vala
src/meson.build

* Use Granite.ValidatedEntry to give feedback about the validation state of the form
* Add error description text
* DRY form validation logic
* Don't rely on connection_entry.visible for validation since widgets are visible by default in GTK4. Instead check if the widget is parented
* Set mnemonic widgets for screen reader

AddDialog: Use Granite.ValidatedEntry, describe errors, DRY

---

src/Widgets/PrinterRow.vala

Fixes chat bubble status icons. Emblem icons are gresourced into Granite 7.4.0

PrinterRow: use emblem status icons
