elementary/switchboard-plug-printers

src/Objects/Job.vala
=> Fix job typos

src/Objects/Printer.vala
=> po: use dpgettext2 instead of dpgettext for better gettext support

src/AddPopover.vala, src/CUPSPkHelper.vala, src/InkLevel.vala, src/Objects/Printer.vala, src/Objects/PrinterManager.vala, src/Plug.vala, src/PrinterList.vala, src/PrinterPage.vala, src/PrinterRow.vala, src/meson.build, vapi/cups.vapi
=> New PrinterManager object to abstract the CUPS api and all the helpers

src/PrinterPage.vala
=> Use Gtk.ModelButton in popover menu

src/Widgets/JobRow.vala
* Organize
* Use var keyword
* Use Granite relative datetime
=> JobRow: Clean up, use relative datetime

src/Widgets/AddDialog.vala
* Move buttons into a buttonbox
* Fix vertical spacing
* Remove unnecessary casts
* Remove extra grids
* Organize
* Add a frame
=> AddDialog: Page 2 cleanup

src/Widgets/PrinterRow.vala
Also remove unnecessary casts and add whitespace for legibility
=> PrinterRow: GObject style

src/Objects/Printer.vala
=> Default label for unnamed printer

src/PrinterList.vala
=> Switch to actionbar

data/printers.appdata.xml.in, meson.build
https://github.com/elementary/switchboard-plug-printers/compare/2.1.7...master
**Changelog:**
<p>Minor updates:</p>
<ul>
<li>Updated translations</li>
</ul>
=> release 2.1.8

data/printers.appdata.xml.in
For better display in Feedback and AppCenter
=> AppData: Add "Settings" to name

data/printers.appdata.xml.in, meson.build
=> Release 2.1.9

src/CUPSNotifier.vala
Fixes #145 
For reasons that are not clear to me, applying a (GLib.DBusSignalCallback) cast to the callback results in some parameters being garbled so the requisite signals to update the sidebar were not being sent.  Removing the cast fixed this.  The callback was also changed so as not to rely on the fine detail of the number of parameters in the Variant.
=> Update sidebar after adding or removing printer

src/Dialogs/AddDialog.vala
=> AddDialog: Show the supported language for each driver.

src/PrinterList.vala, src/Widgets/PrinterRow.vala
Fixes #138 
Basic implementation; may need further styling.
Based on code from the online accounts plug.
=> Use newer add/remove list pattern

src/Views/JobsView.vala
* New copyright header
* GObject style construction
* code style
* button with image and label in GTK4 friendly way
* Use child property
* explicit expands and margins
=> JobsView: GTK4 prep

src/Views/SetupView.vala
* Bump copyright header
* Code style
* Use radiobuttons instead of deprecated modebutton for default side option
* box instead of grid
=> SetupView: GTK 4 Prep

debian/control, debian/copyright, debian/rules
=> Port to GTK 4

src/PrinterList.vala, src/PrinterPage.vala, src/Widgets/PrinterRow.vala, src/meson.build
=> Handle own titlebuttons

src/Dialogs/AddDialog.vala
Fixes #199 
Makes mouse back button work, swipies on touchscreen, etc
=> AddDialog: use NavigationView
